# Generated by Django 5.0.2 on 2024-02-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainmenu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='Taste',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
