# Generated by Django 5.0.2 on 2024-03-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=15)),
                ('Last_name', models.CharField(max_length=15)),
                ('Gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1)),
                ('Phone_number', models.IntegerField()),
            ],
        ),
    ]
