# Generated by Django 5.0.2 on 2024-03-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp1', '0002_customer_table_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_table',
            name='Time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
